### ISSUE TITLE
! Dont try on an A02s ! Device goes black after trying to flash GSI

### ISSUE THREAD

**Issue by RandomUser1321** [mlm-games/twrp_galaxy_m02s#5] opened 2024-08-02 19:08 UTC
DONT TRY IT ON AN A02S THIS IS THE LAST MESSAGE FROM ME ABOUT THIS DEVICE BECAUSE IT HAS BEEN CORRUPTED AND CANT BE SAVED AND WONT TURN ON AND THERE IS NO SIGN OF LIFE

**Comment by mlm-games** [comment] 2024-08-03 02:02
Um u said download was working? Ill remove the text immediately

**Comment by mlm-games** [comment] 2024-08-03 02:03
Did it stop working after the other vbmeta.img from xda or due to something else?

**Comment by mlm-games** [comment] 2024-08-03 02:24
From next time, try to tell what was done till it stopped working so i can get a better idea for solving the problem instead of just removing support for ur device

**Comment by RandomUser1321** [comment] 2024-08-03 02:55
So look thats what I thought so I started flashing stuff like gsi gapps and booted to the system and then I went back to twrp finished some stuff with the gapps cuz it didnt flash and when I booted back to system that was the last I have heard from the device

**Comment by RandomUser1321** [comment] 2024-08-03 02:57
> Did it stop working after the other vbmeta.img from xda or due to something else?

The vbmeta was okay I even used that for a different device that is still stable but after doing some stuff with the twrp I can explain in detail the device just shut off dead and wont start

**Comment by mlm-games** [comment] 2024-08-03 04:54
> So look thats what I thought so I started flashing stuff like gsi gapps and booted to the system and then I went back to twrp finished some stuff with the gapps cuz it didnt flash and when I booted back to system that was the last I have heard from the device

So did touch work initially before you flashed the gsi? The problem could be with the GSI also (like if it was meant for a different arch...)

You can fix it it boots to download (Connect your device to pc and then hold both volume buttons) and then flash samsung fw

**Comment by RandomUser1321** [comment] 2024-08-03 11:27
Yea touch works but Gsi does works I did check I did use the os but I went back to twrp to flash gapps but when I tried to reboot it turned off and never turned on

**Comment by mlm-games** [comment] 2024-08-03 11:32
Before flashing Gapps in twrp everything was fine (as in it rebooted to twrp from gsi) and after that if it had problems then it could be due to the Gapps, Did u use the gapps suggested by them or any external ones like nikgapps?

**Comment by mlm-games** [comment] 2024-08-03 11:35
Oh wait, aren't u supposed to not use the os before flashing gapps? Becoz i saw many roms where they day to immediately reboot to recovery after flashing roms and then flash the gapps (but i havent flashed any rom that required me to do it but the instructions for some are similar to whats said above)

**Comment by RandomUser1321** [comment] 2024-08-03 11:50
not nessecirally I always use the os before flashing gapps also on my other devices I have twrp on and were custom rommed

**Comment by RandomUser1321** [comment] 2024-08-03 11:51
> Before flashing Gapps in twrp everything was fine (as in it rebooted to twrp from gsi) and after that if it had problems then it could be due to the Gapps, Did u use the gapps suggested by them or any external ones like nikgapps?

yep everything was fine I can tell you exactly what gapps I tried to flash and what happened next

**Comment by mlm-games** [comment] 2024-08-03 12:19
> > Before flashing Gapps in twrp everything was fine (as in it rebooted to twrp from gsi) and after that if it had problems then it could be due to the Gapps, Did u use the gapps suggested by them or any external ones like nikgapps?
> 
> yep everything was fine I can tell you exactly what gapps I tried to flash and what happened next

Yes pls continue

**Comment by RandomUser1321** [comment] 2024-08-03 13:13
so on every each one of the gapps I got error 1 I said "aught I can use an alternative app store not a problem" so I went to reboot clicked system and nothing it just died went off never turned on

**Comment by mlm-games** [comment] 2024-08-03 13:18
Can u try connecting it to ur computer and holding top & bottom button to see if it opens download mode, and does it still vibrate when holding the power button? (I am assuming u had it charged above 10% before trying to flash gapps)

**Comment by RandomUser1321** [comment] 2024-08-03 13:49
I have tried that too many times Im gonna retry right now now its connected im pressing yea been 20 seconds of pressing theres nothing showing up I also have odin open if something appears and still nothing

**Comment by mlm-games** [comment] 2024-08-03 14:26
Uh then i guess the problem can be solved with some difficulty - https://xdaforums.com/t/cant-enter-to-download-mode.4048231/post-84737329

**Comment by mlm-games** [comment] 2024-08-03 14:46
But next time if an error comes, then check if it is serious once without getting out of the twrp and if it is serious, then just try to restore ur stock boot.img atleast before doing anything else (Always backup your boot.img and carrier) 

This problem is not caused by the twrp mostly coz u said u tried multiple gapps when it showed error so ill just close the issue after ur mobile's condition improves

**Comment by RandomUser1321** [comment] 2024-08-03 15:14
> Uh then i guess the problem can be solved with some difficulty - https://xdaforums.com/t/cant-enter-to-download-mode.4048231/post-84737329

so thats what I have been doings its been a day im waiting for the battery to drain because its not even making a sound

**Comment by RandomUser1321** [comment] 2024-08-03 15:16
and also it wont work because the only sign of life I have is the windows beep when I connect the device thats also how I know the device isnt dead yet

**Comment by mlm-games** [comment] 2024-08-04 02:25
If it is beeping then i think the difficult method should work (just dont connect to computer before holding ig)

>For a difficult phone
>1. Connect usb to computer but not to phone
>2. Hold down all 3 keys
>3. When it buzzes release power and quickly plug in >usb to phone.
>It might take a few times to get it right.

I think even i had a similar problem and where computer would recognise (but it would also vibrate and thats it)

**Comment by RandomUser1321** [comment] 2024-08-04 12:32
you changed the title wrong btw the gapps couldnt flash the gapps didnt flash at all

**Comment by RandomUser1321** [comment] 2024-08-04 12:55
my phone wont even buzz I just connect it to the pc and the pc does the beep the device has no sign

**Comment by mlm-games** [comment] 2024-08-04 12:57
Hmm yeah will change

**Comment by RandomUser1321** [comment] 2024-08-04 17:30
i mean its been almost 3 days since it just went off but when I connect it to the pc it does a beep it means the device is still alive?

**Comment by mlm-games** [comment] 2024-08-05 00:57
> i mean its been almost 3 days since it just went off but when I connect it to the pc it does a beep it means the device is still alive?

When the computer beeps, did it show the device as qualcomm 9008.. or something like that?

**Comment by mlm-games** [comment] 2024-08-05 00:58
U had said the problem was with the Gapps not flashing right? Did GSI also show an error when flashed?

**Comment by RandomUser1321** [comment] 2024-08-05 13:12
> > i mean its been almost 3 days since it just went off but when I connect it to the pc it does a beep it means the device is still alive?
> 
> When the computer beeps, did it show the device as qualcomm 9008.. or something like that?

well thats the problem the only thing it does is beep nothing after that I also went to device manager and it didnt show it

**Comment by RandomUser1321** [comment] 2024-08-05 13:13
> U had said the problem was with the Gapps not flashing right? Did GSI also show an error when flashed?

the gsi flashed fine the gapps tho gave me error 1

**Comment by RandomUser1321** [comment] 2024-08-05 13:15
> > i mean its been almost 3 days since it just went off but when I connect it to the pc it does a beep it means the device is still alive?
> 
> When the computer beeps, did it show the device as qualcomm 9008.. or something like that?

oh actually I just checked and when I connect it instead of showing it where it should be it shows it in others and it shows as QUSB_BULK

**Comment by mlm-games** [comment] 2024-08-05 13:15
Then i think you dont have the qualcomm drivers

**Comment by RandomUser1321** [comment] 2024-08-05 13:40
cool I got it now it displays as qualcomm HS-USB QDLoader 9008
another weird thing windows is saying its in test mode on the side of the wallpaper?

**Comment by RandomUser1321** [comment] 2024-08-05 14:34
> Check here for drivers - https://xdaforums.com/t/unbrick-flash-stock-rom-1-1-7-global-qdloader-9008-fix-edl-mode-fix.4552965/

I have the drivers it shows as somethin else but other than that nothing else I notice what do I do next?

**Comment by RandomUser1321** [comment] 2024-08-05 14:51
> Edl - qualcomm emergency download mode so ig u can flash with samsung firmware using odin like download mode

okay how do I get that and how do I boot to edl mode I tried looking and didnt find anything useful

**Comment by mlm-games** [comment] 2024-08-05 14:51
Just check once if it recognises in Odin

**Comment by RandomUser1321** [comment] 2024-08-05 15:20
> Just check once if it recognises in Odin

odin isnt detecting any device

**Comment by mlm-games** [comment] 2024-08-05 15:35
According to the post, I think yes

**Comment by RandomUser1321** [comment] 2024-08-05 15:37
happy to hear we are making progress what do I do next? since odin isnt really working...

**Comment by mlm-games** [comment] 2024-08-05 15:41
> happy to hear we are making progress what do I do next? since odin isnt really working...

Me too

> > ```
> > case 1:
> > You will have "Qualcomm HS-USB QDLoader 9008" device at your Windows devices list in device manager. (EDL mode)
> > 
> > case 2:
> > You will have "Qualcomm hs-usb diagnostics 900e" device at your Windows devices list in device manager.
> > 
> > 
> > 2. Download[ Flash Tool](https://fastupload.io/We4eKLawzSHflxU/file) (Alternate [Link](https://drive.google.com/file/d/1qOJFObio-gKkWEkP5CzU56tNhN54j0As/view?usp=share_link)).
> > 
> > Rom is included in Flash Tool.
> > 
> > 
> > Note: If you you have phone(1) in Qualcomm HS-USB QDLoader 9008 mode [Case 1] then simply use Flash Tool to flash stock rom as its already in EDL mode.
> > 
> >     Run Tool
> >     Mark the Option FIRMWARE FLASH.
> >     Connect phone in Edl (9008 mode).
> >     Click 'start' button
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It is mentioned in the xda link i sent previously
> 
> so if it detects my device as qualcomm HS-USB QDLoader 9008 it means its already in edl?

Well i thought that flash tool was odin, mb 

Just check that flash tool in the xda post and follow the steps with samsung's firmware for A02s

**Comment by RandomUser1321** [comment] 2024-08-05 15:43
well here comes another issue upon opening the .exe this program is made for the Nothing Phone 1 heres a photo of the flash tool
![image](https://github.com/user-attachments/assets/83545579-bf78-4ee7-ae1d-9e438b90674d)

**Comment by mlm-games** [comment] 2024-08-05 15:46
> well here comes another issue upon opening the .exe this program is made for the Nothing Phone 1 heres a photo of the flash tool ![image](https://private-user-images.githubusercontent.com/177152340/355162756-83545579-bf78-4ee7-ae1d-9e438b90674d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzI5NjIsIm5iZiI6MTcyMjg3MjY2MiwicGF0aCI6Ii8xNzcxNTIzNDAvMzU1MTYyNzU2LTgzNTQ1NTc5LWJmNzgtNGVlNy1hZTFkLTllNDM4YjkwNjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxNTQ0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzM5NjY0YzE5NjRkOTNiZTExZGEzZjUyNzU3NTRjOWY2ZWNlM2YxZWM2MjM0MzQ0OWM3YmMwNGQ1Y2I3NmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.su0o7K8_4hJslmDENespCs_LHnTjanUYyZEfoXYRRwk)

Oh... Will have to search for samsung related ones ig

I'll tell if i find anything related

**Comment by RandomUser1321** [comment] 2024-08-05 15:49
so I have found something its called QPST or Qualcomm Product Support Tool I havent tried that yet im still reading the page

**Comment by RandomUser1321** [comment] 2024-08-05 16:50
> > i mean its been almost 3 days since it just went off but when I connect it to the pc it does a beep it means the device is still alive?
> 
> When the computer beeps, did it show the device as qualcomm 9008.. or something like that?

yea so looking back I was panicking it didnt turn on so I started doing key combaniations and it ended up in edl mode

**Comment by RandomUser1321** [comment] 2024-08-06 18:00
I tried multiple flash tools and I tried restarting the phone and I am just wasting too much time on it and I think I should just end it with the device since I also got this device for free when my brother pre ordered his S21 ultra back in 2021 and this phone was pretty much not it and even if I get to save it it will still run very poorly and its not really worth it

**Comment by mlm-games** [comment] 2024-08-07 00:53
Normally GSIs only contain the system.img, and Gapps should modify only that (super.img contains boot.img, system.img, vendor.img,  and another .img and you must have noticed that GSIs are just plain system.img while flashing) so idk what error u had recieved, maybe it was not related to Gapps and it might have been related to something else in the previous attempts. I can only speculate

Hmm yeah i was also not able to find a QPST file for the device and i dont know how they made available. 

Well next time this should help you not restart in case of an error (twrp warns you for the same and u could even flash samsung firmware directly if u didnt backup) and backup before flashing any files in twrp or any other rec. so that you can atleast reset the boot.img and then copy the logs also coz thats how the problem could be identified and solved.

**Closed** 2024-08-07 10:24 UTC

**Comment by ravindu644** [comment] 2024-10-03 03:45
This happened because the A02s has a different size for the super partition.

I guess this is fixable by repartitioning the device again using a PIT file.

You just need to hard reboot immediately (even if the screen is turned off and showing no signs of life). Pressing Volume Down and Power will turn the power off for the display after 7 seconds. It's barely noticeable when direct sunlight is applied to the display, so immediately press both Volume keys after that, and the device will enter Download Mode.

**Comment by ImAcuer** [comment] 2025-05-08 18:23
> This happened because the A02s has a different size for the super partition.
> 
> I guess this is fixable by repartitioning the device again using a PIT file.
> 
> You just need to hard reboot immediately (even if the screen is turned off and showing no signs of life). Pressing Volume Down and Power will turn the power off for the display after 7 seconds. It's barely noticeable when direct sunlight is applied to the display, so immediately press both Volume keys after that, and the device will enter Download Mode.

Hi (late reply because I forgot about my a02s) my phone had a different issue my bootloader has been wiped I couldnt enter download mode or recovery the only way to fix this phone is either by reflashing the bootloader or replacing the storage
reflashing the bootloader required me files samsung do not provide making the repair impossible without having to spend money I no longer had the A02s by the time you wrote that oh and GSI flash was successful but it only booted once

**Comment by ImAcuer** [comment] 2025-05-08 18:29
> Normally GSIs only contain the system.img, and Gapps should modify only that (super.img contains boot.img, system.img, vendor.img, and another .img and you must have noticed that GSIs are just plain system.img while flashing) so idk what error u had recieved, maybe it was not related to Gapps and it might have been related to something else in the previous attempts so can only speculate...
> 
> Hmm yeah i was also not able to find a QPST file for the device and i dont know how they made available.
> 
> Well next time this should help you not restart in case of an error (twrp warns you for the same and u could even flash samsung firmware directly if u didnt backup) and backup before flashing any files in twrp or any other rec. so that you can atleast reset the boot.img and then copy the logs also coz thats how the problem could be identified and solved.

Hi so after deeper digging on qualcomm 9008 mode something has either corrupted my bootloader or wiped it I am not blaming it on your TWRP build since I have no idea what led to it the GSI booted fine at the start until I flashed those GAPPS files that only gave me errors
I didnt wipe any partitions before rebooting
I tried flashing 3 different GAPPS
nikgapps
beangapps (unsure)
and mindthegapps
the GSI I tried was from the official treble GSI website only thing I remember about the gsi it was arm32 (which is what the app recommended me)
